version: '3.8'

services:
  mysql-app-db:
    image: mysql:8
    container_name: mysql-app-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    restart: always